import Foundation

enum CLI {
    struct Status: Decodable {
        let loggedIn: Bool
        let email: String?
        let orgName: String?
        let subscriptionType: String?
        let authMethod: String?
    }

    static let executable: String? = {
        for candidate in [
            "/opt/homebrew/bin/claude",
            "/usr/local/bin/claude",
            "\(NSHomeDirectory())/.local/bin/claude",
        ] where FileManager.default.isExecutableFile(atPath: candidate) {
            return candidate
        }
        return which("claude")
    }()

    static func status() -> Status? {
        guard let output = run(["auth", "status"]) else { return nil }
        guard let data = output.data(using: .utf8) else { return nil }
        return try? JSONDecoder().decode(Status.self, from: data)
    }

    private static func which(_ name: String) -> String? {
        run(executable: "/usr/bin/which", ["-a", name])?
            .split(separator: "\n")
            .first
            .map(String.init)
    }

    private static func run(_ arguments: [String]) -> String? {
        guard let executable else { return nil }
        return run(executable: executable, arguments)
    }

    private static func run(executable: String, _ arguments: [String]) -> String? {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()

        do { try process.run() } catch { return nil }

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else { return nil }
        return String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}

enum BrowserChoice: Codable, Equatable {
    case chromeProfile(String)
    case chrome(ChromeChannel, String)
    case firefox
    case safari
    case systemDefault

    var label: String { label(chromeNames: [:]) }

    func label(chromeNames: [String: String]) -> String {
        switch self {
        case .chromeProfile(let profile):
            return label(channel: .stable, profile: profile, chromeNames: chromeNames)
        case .chrome(let channel, let profile):
            return label(channel: channel, profile: profile, chromeNames: chromeNames)
        case .firefox: return "Firefox"
        case .safari: return "Safari"
        case .systemDefault: return "System default"
        }
    }

    private func label(channel: ChromeChannel, profile: String, chromeNames: [String: String]) -> String {
        let named = chromeNames[ChromeProfiles.key(channel, profile)] ?? profile
        return "\(channel.label) — \(named)"
    }

    var overridesBrowser: Bool { openCommand != nil }

    func environmentAssignment() throws -> String? {
        guard let script = try wrapperScript() else { return nil }
        return "BROWSER=\(CLI.shellQuote(script.path))"
    }

    var openCommand: String? {
        switch self {
        case .chromeProfile(let profile):
            return BrowserChoice.chromeCommand(channel: .stable, profile: profile)
        case .chrome(let channel, let profile):
            return BrowserChoice.chromeCommand(channel: channel, profile: profile)
        case .firefox:
            return "open -a Firefox \"$@\""
        case .safari:
            return "open -a Safari \"$@\""
        case .systemDefault:
            return nil
        }
    }

    func wrapperScript() throws -> URL? {
        guard let command = openCommand else { return nil }

        let dir = StateDirectory.url.appendingPathComponent("browsers")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let url = dir.appendingPathComponent(slug + ".sh")
        let body = [
            "#!/bin/sh",
            "# Generated by Hats. Opens one URL in a specific browser identity.",
            "exec " + command,
            "",
        ].joined(separator: "\n")

        try body.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: url.path
        )
        return url
    }

    static func chromeCommand(channel: ChromeChannel, profile: String) -> String {
        "open -na " + CLI.shellQuote(channel.application)
            + " --args --profile-directory=" + CLI.shellQuote(profile) + " \"$@\""
    }

    var slug: String {
        switch self {
        case .chromeProfile(let profile):
            return "chrome-" + BrowserChoice.safeComponent(profile, fallback: "profile")
        case .chrome(let channel, let profile):
            return BrowserChoice.safeComponent(channel.rawValue, fallback: "chrome")
                + "-" + BrowserChoice.safeComponent(profile, fallback: "profile")
        case .firefox: return "firefox"
        case .safari: return "safari"
        case .systemDefault: return "default"
        }
    }

    static func safeComponent(_ value: String, fallback: String) -> String {
        let allowed = Set("abcdefghijklmnopqrstuvwxyz0123456789-_.")
        let lowered = value.lowercased()
        var reduced = String(lowered.map { allowed.contains($0) ? $0 : "-" })
        while reduced.contains("--") {
            reduced = reduced.replacingOccurrences(of: "--", with: "-")
        }
        while reduced.contains("..") {
            reduced = reduced.replacingOccurrences(of: "..", with: ".")
        }
        reduced = reduced.trimmingCharacters(in: CharacterSet(charactersIn: "-."))
        if reduced.isEmpty || reduced == "." || reduced == ".." { return fallback }
        if reduced.contains("/") || reduced.contains(":") { return fallback }
        return String(reduced.prefix(64))
    }

    static func available() -> [BrowserChoice] {
        var choices: [BrowserChoice] = ChromeChannel.allCases.flatMap { channel in
            channel.profiles.map { BrowserChoice.chrome(channel, $0) }
        }
        if FileManager.default.fileExists(atPath: "/Applications/Firefox.app") {
            choices.append(.firefox)
        }
        choices.append(.safari)
        return choices
    }
}
