import Foundation

enum CLI {
    struct Status: Decodable {
        let loggedIn: Bool
        let email: String?
        let orgName: String?
        let subscriptionType: String?
        let authMethod: String?
    }

    static let executable: String? = {
        for candidate in [
            "/opt/homebrew/bin/claude",
            "/usr/local/bin/claude",
            "\(NSHomeDirectory())/.local/bin/claude",
        ] where FileManager.default.isExecutableFile(atPath: candidate) {
            return candidate
        }
        return which("claude")
    }()

    static func status() -> Status? {
        guard let output = run(["auth", "status"]) else { return nil }
        guard let data = output.data(using: .utf8) else { return nil }
        return try? JSONDecoder().decode(Status.self, from: data)
    }

    static func loginCommand(email: String?, browser: BrowserChoice?) throws -> String {
        var parts: [String] = []
        if let browser, let assignment = try browser.environmentAssignment() {
            parts.append(assignment)
        }
        parts.append(shellQuote(executable ?? "claude"))
        parts.append("auth")
        parts.append("login")
        if let email, !email.isEmpty {
            parts.append("--email")
            parts.append(shellQuote(email))
        }
        return parts.joined(separator: " ")
    }

    private static func which(_ name: String) -> String? {
        run(executable: "/usr/bin/which", ["-a", name])?
            .split(separator: "\n")
            .first
            .map(String.init)
    }

    private static func run(_ arguments: [String]) -> String? {
        guard let executable else { return nil }
        return run(executable: executable, arguments)
    }

    private static func run(executable: String, _ arguments: [String]) -> String? {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()

        do { try process.run() } catch { return nil }

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else { return nil }
        return String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}

enum BrowserChoice: Codable, Equatable {
    case chromeProfile(String)
    case firefox
    case safari
    case systemDefault

    var label: String { label(chromeNames: [:]) }

    func label(chromeNames: [String: String]) -> String {
        switch self {
        case .chromeProfile(let profile): return "Chrome — \(chromeNames[profile] ?? profile)"
        case .firefox: return "Firefox"
        case .safari: return "Safari"
        case .systemDefault: return "System default"
        }
    }

    var overridesBrowser: Bool { openCommand != nil }

    func environmentAssignment() throws -> String? {
        guard let script = try wrapperScript() else { return nil }
        return "BROWSER=\(CLI.shellQuote(script.path))"
    }

    private var openCommand: String? {
        switch self {
        case .chromeProfile(let profile):
            let quoted = CLI.shellQuote(profile)
            return "open -na 'Google Chrome' --args --profile-directory=" + quoted + " \"$@\""
        case .firefox:
            return "open -a Firefox \"$@\""
        case .safari:
            return "open -a Safari \"$@\""
        case .systemDefault:
            return nil
        }
    }

    private func wrapperScript() throws -> URL? {
        guard let command = openCommand else { return nil }

        let dir = StateDirectory.url.appendingPathComponent("browsers")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let url = dir.appendingPathComponent(slug + ".sh")
        let body = [
            "#!/bin/sh",
            "# Generated by Hats. Opens one URL in a specific browser identity.",
            "exec " + command,
            "",
        ].joined(separator: "\n")

        try body.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: url.path
        )
        return url
    }

    private var slug: String {
        switch self {
        case .chromeProfile(let profile):
            return "chrome-" + BrowserChoice.safeComponent(profile, fallback: "profile")
        case .firefox: return "firefox"
        case .safari: return "safari"
        case .systemDefault: return "default"
        }
    }

    static func safeComponent(_ value: String, fallback: String) -> String {
        let allowed = Set("abcdefghijklmnopqrstuvwxyz0123456789-_.")
        let lowered = value.lowercased()
        var reduced = String(lowered.map { allowed.contains($0) ? $0 : "-" })
        while reduced.contains("--") {
            reduced = reduced.replacingOccurrences(of: "--", with: "-")
        }
        while reduced.contains("..") {
            reduced = reduced.replacingOccurrences(of: "..", with: ".")
        }
        reduced = reduced.trimmingCharacters(in: CharacterSet(charactersIn: "-."))
        if reduced.isEmpty || reduced == "." || reduced == ".." { return fallback }
        if reduced.contains("/") || reduced.contains(":") { return fallback }
        return String(reduced.prefix(64))
    }

    static func availableChromeProfiles() -> [String] {
        let root = URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent("Library/Application Support/Google/Chrome")
        guard let entries = try? FileManager.default.contentsOfDirectory(atPath: root.path) else {
            return []
        }
        return entries
            .filter { $0 == "Default" || $0.hasPrefix("Profile ") }
            .sorted()
    }

    static func available() -> [BrowserChoice] {
        var choices: [BrowserChoice] = availableChromeProfiles().map { .chromeProfile($0) }
        if FileManager.default.fileExists(atPath: "/Applications/Firefox.app") {
            choices.append(.firefox)
        }
        choices.append(.safari)
        return choices
    }
}

enum Terminal {
    static var logURL: URL {
        stateDir.appendingPathComponent("last-login.log")
    }

    static let scriptName = "login.command"

    static var doneMarkerPath: String {
        stateDir.appendingPathComponent("login-done").path
    }

    static var scriptPath: String {
        stateDir.appendingPathComponent(scriptName).path
    }

    static func hasALoginInFlight(isDone: Bool, scriptExists: Bool) -> Bool {
        !isDone && scriptExists
    }

    static func hasALoginInFlight() -> Bool {
        hasALoginInFlight(
            isDone: isDone,
            scriptExists: FileManager.default.fileExists(atPath: scriptPath)
        )
    }

    static func isScriptRunning(among commandLines: [String], scriptPath: String) -> Bool {
        commandLines.contains { $0.contains(scriptPath) }
    }

    static let scriptCheckBudget: TimeInterval = 1

    static func isScriptRunning() -> Bool? {
        guard let table = ProcessTable.read(
            ["-eo", "command="],
            within: scriptCheckBudget
        ) else { return nil }
        let lines = table.split(separator: "\n").map(String.init)
        return isScriptRunning(among: lines, scriptPath: scriptPath)
    }

    static func removeScript() {
        try? FileManager.default.removeItem(atPath: scriptPath)
    }

    static func clearDoneMarker() {
        try? FileManager.default.removeItem(atPath: doneMarkerPath)
    }

    static var isDone: Bool {
        FileManager.default.fileExists(atPath: doneMarkerPath)
    }

    private static var stateDir: URL {
        StateDirectory.url
    }

    static func open(command: String) throws {
        try FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true)

        clearDoneMarker()
        let script = stateDir.appendingPathComponent(scriptName)
        let log = logURL
        let body = [
            "#!/bin/sh",
            "# Generated by Hats. Runs one login and keeps its output.",
            "clear",
            "echo 'Signing in — a browser window should open.'",
            "echo",
            "{ " + command + " ; } 2>&1 | tee " + CLI.shellQuote(log.path),
            "echo",
            "echo 'Done — choose Refresh in the menu to pick this up.'",
            "printf 'Press any key to close... '",
            "stty -echo 2>/dev/null",
            "dd bs=1 count=1 >/dev/null 2>&1",
            "stty echo 2>/dev/null",
            "echo",
            "touch " + CLI.shellQuote(doneMarkerPath),
            "exit 0",
            "",
        ].joined(separator: "\n")

        try body.write(to: script, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: script.path
        )

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        process.arguments = ["-a", "Terminal", script.path]
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw KeychainError(
                operation: "open Terminal",
                detail: "`open` exited with status \(process.terminationStatus)"
            )
        }
    }
}
